# Generated by Django 4.1.1 on 2022-10-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='nip',
            new_name='nim',
        ),
    ]
